import React from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { ArrowRight, Brain, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";

interface ClimateAIInsightsProps {
  isLoading?: boolean;
}

// This component would ideally use the OpenRouter AI to generate personalized climate insights
// However, due to current credit limitations in OpenRouter, we're using placeholder content
const ClimateAIInsights: React.FC<ClimateAIInsightsProps> = ({ isLoading = false }) => {
  if (isLoading) {
    return (
      <Card className="w-full">
        <CardHeader>
          <Skeleton className="h-6 w-[250px] mb-2" />
          <Skeleton className="h-4 w-[300px]" />
        </CardHeader>
        <CardContent className="space-y-4">
          <Skeleton className="h-20 w-full" />
          <div className="space-y-2">
            <Skeleton className="h-4 w-[90%]" />
            <Skeleton className="h-4 w-[95%]" />
            <Skeleton className="h-4 w-[85%]" />
            <Skeleton className="h-4 w-[90%]" />
          </div>
          <div className="flex justify-start gap-2">
            <Skeleton className="h-6 w-20 rounded-full" />
            <Skeleton className="h-6 w-20 rounded-full" />
          </div>
        </CardContent>
        <CardFooter>
          <Skeleton className="h-9 w-full" />
        </CardFooter>
      </Card>
    );
  }

  // In a real implementation, this would be generated by the AI based on:
  // 1. Local weather patterns
  // 2. Seasonal considerations 
  // 3. Regional climate issues
  // 4. User preferences/profile
  const aiGeneratedInsight = `
    Based on Hanoi's climate patterns and your local environmental conditions, here are some personalized recommendations:
    
    The monsoon season in Hanoi leads to increased flooding risks. Consider supporting local water management initiatives and ensuring proper drainage around your home.
    
    Hanoi's air quality can be challenging, especially during winter temperature inversions. Try using air purifiers at home and wearing masks during high-pollution days.
    
    The region's rich biodiversity is under threat from urban expansion. Supporting local conservation efforts and creating wildlife-friendly spaces can make a difference.
    
    Energy demand peaks during hot summers. Installing ceiling fans can reduce air conditioning usage by up to 40%, significantly lowering your carbon footprint.
  `;

  return (
    <Card className="w-full">
      <CardHeader>
        <div className="flex justify-between items-start">
          <div>
            <CardTitle className="text-xl font-semibold flex items-center gap-2">
              <Brain className="h-5 w-5 text-primary" />
              AI Climate Insights
            </CardTitle>
            <CardDescription>
              Personalized climate action recommendations for your region
            </CardDescription>
          </div>
          <Badge variant="outline" className="bg-primary/10 text-primary">
            AI Generated
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="text-sm whitespace-pre-line">
          {aiGeneratedInsight}
        </div>
        
        <div className="flex flex-wrap gap-2 mt-2">
          <Badge variant="secondary">Local Action</Badge>
          <Badge variant="secondary">Adaptation</Badge>
          <Badge variant="secondary">Energy Efficiency</Badge>
          <Badge variant="secondary">Conservation</Badge>
        </div>
      </CardContent>
      <CardFooter>
        <Button className="w-full flex items-center gap-2" disabled>
          <span>Get Personalized Insights</span> 
          <RefreshCw className="h-4 w-4" />
        </Button>
        <p className="text-xs text-muted-foreground text-center mt-2">
          Note: This feature requires an active OpenRouter API subscription
        </p>
      </CardFooter>
    </Card>
  );
};

export default ClimateAIInsights;